# -*- coding: utf-8 -*-
"""Быстрое обновление цен с WB. python scripts/sync-prices.py"""
from __future__ import annotations

import json
import re
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(r"d:\Getstafff\getstaff2")
JS_DIR = ROOT / "js"
DEST = -1257786
BATCH = 40
DELAY = 0.8
SELLER = 55354

UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)


def load_products():
    raw = (JS_DIR / "products.data.js").read_text(encoding="utf-8")
    raw = re.sub(r"/\*.*?\*/", "", raw, flags=re.S)
    raw = raw.replace("const PRODUCTS_DATA = ", "", 1).rstrip().rstrip(";")
    return json.loads(raw)


def fetch_batch(ids: list[int]) -> dict:
    nm = ";".join(str(i) for i in ids)
    url = (
        f"https://card.wb.ru/cards/v2/detail?appType=1&curr=rub"
        f"&dest={DEST}&nm={nm}"
    )
    req = urllib.request.Request(url, headers={"User-Agent": UA, "Accept": "application/json"})
    with urllib.request.urlopen(req, timeout=40) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    out = {}
    for p in data.get("data", {}).get("products") or []:
        sz = (p.get("sizes") or [{}])[0].get("price") or {}
        price = round((sz.get("product") or p.get("salePriceU") or 0) / 100)
        basic = round((sz.get("basic") or p.get("priceU") or 0) / 100)
        total_qty = p.get("totalQuantity")
        if total_qty is None:
            total_qty = 0
            for size in p.get("sizes") or []:
                for st in size.get("stocks") or []:
                    total_qty += st.get("qty") or 0
        out[str(p["id"])] = {
            "price": price or basic or 0,
            "oldPrice": basic if basic > price else None,
            "inStock": total_qty > 0,
            "rating": p.get("reviewRating") or p.get("rating"),
            "reviews": p.get("feedbacks"),
        }
    return out


def main():
    print("=== Обновление цен WB ===")
    data = load_products()
    products = data.get("products") or []
    ids = [int(p.get("wbId") or p["id"]) for p in products]
    print(f"Товаров: {len(ids)}")

    all_map: dict = {}
    batches = (len(ids) + BATCH - 1) // BATCH
    for bi in range(batches):
        chunk = ids[bi * BATCH : (bi + 1) * BATCH]
        print(f"  партия {bi + 1}/{batches}…", flush=True)
        for attempt in range(3):
            try:
                all_map.update(fetch_batch(chunk))
                break
            except Exception as e:
                print(f"    ошибка: {e}, повтор…")
                time.sleep(2 + attempt)
        time.sleep(DELAY)

    changed = 0
    missing = 0
    for p in products:
        pr = all_map.get(str(p["id"]))
        if not pr or not pr["price"]:
            missing += 1
            continue
        if p.get("price") != pr["price"] or p.get("oldPrice") != pr["oldPrice"]:
            changed += 1
        p["price"] = pr["price"]
        p["oldPrice"] = pr["oldPrice"]
        p["inStock"] = pr["inStock"]
        if pr.get("rating") is not None:
            p["rating"] = pr["rating"]
        if pr.get("reviews") is not None:
            p["reviews"] = pr["reviews"]

    if not all_map:
        print("FAIL: WB blocked requests (403). Run this script from your home PC/VPN in Russia.")
        print("No files were overwritten.")
        raise SystemExit(2)

    synced = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    data["syncedAt"] = synced

    header = (
        f"/* AUTO-GENERATED by scripts/sync-prices.py — {synced} */\n"
        f"/* Prices from Wildberries seller {SELLER} */\n"
    )
    (JS_DIR / "products.data.js").write_text(
        header + "const PRODUCTS_DATA = " + json.dumps(data, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )

    prices = {
        "syncedAt": synced,
        "sellerId": SELLER,
        "items": {
            p["id"]: {"price": p["price"], "oldPrice": p.get("oldPrice")}
            for p in products
        },
    }
    (JS_DIR / "prices.json").write_text(
        json.dumps(prices, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    samples = [
        f"{p['id']}: {p['price']} ₽ — {p['name'][:45]}"
        for p in products[:6]
    ]
    print(f"Изменилось цен: {changed}")
    print(f"Без ответа WB: {missing}")
    print("Примеры:")
    for s in samples:
        print(" ", s)
    print("✓ products.data.js + prices.json")


if __name__ == "__main__":
    main()
